### ISSUE TITLE
Where can I get the dataset?

### ISSUE THREAD

**Issue by CarlHoo** [LouisChen1992/Deep_Mortgage_Risk_RNN#8]
root@ubuntu02:/# python run_data_process.py --dataset subprime --bucket 5
Processing data with lValue 1...
Traceback (most recent call last):
  File "run_data_process.py", line 40, in <module>
    for tValue in os.listdir(os.path.join(path_src,str(lValue))):
FileNotFoundError: [Errno 2] No such file or directory: '/root/data/RNNdata/subprime/1'

**Comment by LouisChen1992** [comment]
We do not share our data.

**Comment by LouisChen1992** [comment]
> root@ubuntu02:/# python run_data_process.py --dataset subprime --bucket 5
> Processing data with lValue 1...
> Traceback (most recent call last):
> File "run_data_process.py", line 40, in 
> for tValue in os.listdir(os.path.join(path_src,str(lValue))):
> FileNotFoundError: [Errno 2] No such file or directory: '/root/data/RNNdata/subprime/1'

Unfortunately, we do not share our data.
